name: Build with Maven

on:
  workflow_call:
    inputs:
      pom-file-path:
        description: 'Path to the pom.xml file'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print working directory
      run: pwd
    - name: Build with Maven
      run: mvn -B package --file {{inputs.pom-file-path}}
    - name: Print working direct
      run: pwd
