name: Build and Push Docker Image

on:
  workflow_call:
    # inputs:
    #   docker_username:
    #     required: true
    #     type: string
    #   docker_password:
    #     required: true
    #     type: string

jobs:
  build-push:
    runs-on: hexa-runner

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ganesh7709/github-test-repo:latest
