name: Build with Maven

on:
  workflow_call:
    inputs:
      pom-file-path:
        description: 'Path to the pom.xml file'
        required: true
        type: string

jobs:
  build:
    runs-on: hexa-runner

    steps:
    # - name: Print working directory
    #   run: pwd
    # - name: List files for debugging
    #   run: ls -R
    - name: Build with Maven
      run: | 
            $env:MAVEN_HOME = "C:\maven\apache-maven-3.9.9"
            $env:PATH += ";C:\maven\apache-maven-3.9.9\bin"
            mvn -version
            mvn -B package --file ${{inputs.pom-file-path}}
           
    # - name: Print working direct
    #   run: pwd
