name: Checkout Code

on:
  workflow_call:

jobs:
  checkout:
    runs-on: hexa-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: List files for debugging
      run: ls -R
    - name: Print working directory
      run: pwd
      
