name: Gradle Workflow

on:
  workflow_call:
    inputs:
      gradle-task:
        required: true
        type: string

jobs:
  gradle-job:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle Task
        run: ./gradlew ${{ inputs.gradle-task }}
