name: Log in to Docker Hub

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string

jobs:
  login:
    runs-on: hexa-runner

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
