name: Set Up JDK

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  setup-jdk:
    runs-on: hexa-runner
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    
