name: Set Up JDK

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  setup-jdk:
    runs-on: hexa-runner
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'
    # - name: Set up Maven
    #   run: |
    #     $env:MAVEN_HOME = "C:\maven\apache-maven-3.9.9"
    #     $env:PATH += ";C:\maven\apache-maven-3.9.9\bin"
    #     mvn -version
    
